version: '3.3'

services:
  api:
    image: jcdemo/flaskapp:latest
    restart: on-failure
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hello_world
      MYSQL_DATABASE: ad_provider
      MYSQL_USER: root
      MYSQL_PASSWORD: gg123456
  cache:
    image: redis:latest
# volumes:
#   cached: ..:/workspace:cached